.TH pass-env 1 "2017 April 24" "Version 1.0.0" "User Commands"

.SH NAME
pass-env - a password-store extension manage env vars

.SH SYNOPSIS
.B pass
env
[
.I pass-name
]

.SH DESCRIPTION

.BR pass(1)
proposes a format to store meta data in the password file.
The password is stored in the first line followed by data like the URL, username and other meta data in the following lines.
.B pass-env
is an extension for the
.BR pass(1)
that allows users to manage env vars.

.SH COMMANDS
.TP
\fBenv\fP \fIpass-name\fP
.br
DTODO
.TP
\fBtailedit\fP \fIpass-name\fP
Open the password file in the editor omitting the first line. When saving the first line is prepended.

.SH SEE ALSO
.BR pass (1)

.SH AUTHOR
thomaslaurenson


.SH HOME
.I https://github.com/thomaslaurenson/pass-env


.SH REPORTING BUGS
.I https://github.com/thomaslaurenson/pass-env/issues

.SH LICENSE
Copyright \(co 2026 Thomas Laurenson.
.PP
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
.PP
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
