name: Tag and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml
  release:
    needs: [lint, test]
    uses: ./.github/workflows/release.yml
    secrets: inherit
