name: Test

on: workflow_call

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Run tests
        run: make test
